Fix for ignore suggestion on the new editor
Clemens-E/obsidian-languagetool-plugin pull request #55
Opened 2022-03-09 13:42 UTC by ruohki

It seems that codemirror does not select the text when you rightclick it so the selection.from and selection.to were the same number wich lead into the error.

It appears that just clearing the underline part solves this issue

Related issue https://github.com/Clemens-E/obsidian-languagetool-plugin/issues/53

2022-03-09 13:59 UTC, ruohki commented
sorry for the mailspam :)

2022-03-09 22:08 UTC, mgmeyers requested changes
@ruohki Thanks for catching this! Could you also make this same update to the `clearUnderlineEffect` above? Other than that this is perfect.

2022-03-10 00:55 UTC, ruohki commented
Yeh will do once i wakeup, i just noticed the issue on the ignore suggestion menu entry. Normal replacement works fine

2022-03-11 17:44 UTC, mgmeyers approved these changes

2022-03-11 17:46 UTC, merged

2022-03-11 17:48 UTC, mgmeyers commented
Tested and verified that everything looks good!

2022-03-11 19:33 UTC, ruohki commented
Perfect :)

Von meinem iPhone gesendet

> Am 11.03.2022 um 18:48 schrieb Matthew Meyers ***@***.***>:
> 
> ﻿
> Tested and verified that everything looks good!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.